tar: use SAVE_SORT_INODE if D_INO_IN_DIRENT is defined
SAVEDIR_SORT_INODE is defined if D_INO_IN_DIRENT is defined.

* src/tar.c (sort_mode_arg): Use SAVEDIR_SORT_INODE if D_INO_IN_DIRENT
is defined. Otherwise SAVEDIR_SORT_NONE.

-----
  CC       tar.o
  tar.c:1352: error: `SAVEDIR_SORT_INODE' undeclared here (not in a function)
  tar.c:1352: error: initializer element is not constant
  tar.c:1352: error: (near initialization for `sort_mode_flag[2]')
  tar.c:1354: error: negative width in bit-field `_gl_verify_error_if_negative'